spring.application.name=myedulink-backend
# Server
server.port=8080
# Désactivation temporaire de la DB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
