# Nom de l'application
spring.application.name=myedulink-backend

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/edulink_db
spring.datasource.username=youva.kadji
spring.datasource.password=  # vide si pas de mot de passe
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port (optionnel)
server.port=8080
